src/Chirp.Web/Pages/PrivateTimeline.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Chirp.Core;

namespace Chirp.Web.Pages;

/// <summary>
/// Razor page representing the private timeline of an author.
/// </summary>
public class PrivateTimelineModel : PageModel
{

    private readonly ICheepRepository _cheepRepo;
    private readonly IAuthorRepository _authorRepo;

    /// <summary>
    /// Gets or sets the list of cheeps displayed on a private timeline.
    /// </summary>
    public List<CheepDTO> Cheeps { get; set; }
    /// <summary>
    /// Gets or sets the author associated with a private timeline.
    /// </summary>
    public AuthorDTO? author { get; set; }

    /// <summary>
    /// Gets or sets a dictionary saying whether a user is following an author or not.
    /// </summary>
    public Dictionary<string, bool>? IsUserFollowingAuthor { get; set; }

    /// <summary>
    /// Gets or sets the total cheeps. 
    /// </summary>
    public int TotalCheeps { get; set; }

    /// <summary>
    /// Gets or sets the current page number.
    /// </summary>
    public int PageNumber { get; set; }

    /// <summary>
    /// Gets or sets the number of cheeps allowed per page.
    /// </summary>
    public int CheepsPerPage { get; set; }

    /// <summary>
    /// Gets or sets the redirection URL.
    /// </summary>
    public string? RedirectUrl { get; set; }

    /// <summary>
    /// Gets or sets a new cheep.
    /// </summary>
    [BindProperty]
    public string? NewCheep { get; set; }

    /// <summary>
    /// Initializes a new instance of private timeline.
    /// </summary>
    /// <param name="cheepRepo"></param>
    /// <param name="authorRepo"></param>
    public PrivateTimelineModel(ICheepRepository cheepRepo, IAuthorRepository authorRepo)
    {
        Cheeps = new();
        _cheepRepo = cheepRepo;
        _authorRepo = authorRepo;
        PageNumber = 1;
        CheepsPerPage = 32;
    }

    /// <summary>
    /// Handles HTTP GET requests for the private timeline.
    /// </summary>
    /// <param name="pageNumber"></param>
    /// <returns>The IActionResult representing the result of the operation.</returns>
    public async Task<ActionResult> OnGet(int? pageNumber)
    {
        string username = User.Identity?.Name!;
        if (pageNumber.HasValue)
        {
            PageNumber = pageNumber.Value;
        }
        TotalCheeps = await _authorRepo.GetTotalCheepCountFromFollowersAndAuthor(username);
        Cheeps = await _cheepRepo.GetPrivateTimelineCheeps(username, CheepsPerPage, PageNumber);

        if (User.Identity?.IsAuthenticated == true)
        {
            IsUserFollowingAuthor = new();
            foreach (CheepDTO cheep in Cheeps)
            {
                IsUserFollowingAuthor[cheep.author] = await FindIsUserFollowingAuthor(cheep.author, User.Identity?.Name!);
            }
        }
        RedirectUrl ??= Url.Content("/private");

        return Page();
    }

    /// <summary>
    /// Handles HTTP POST requests for the private timeline.
    /// </summary>
    /// <returns>The IActionResult representing the result of the operation.</returns>
    public async Task<IActionResult> OnPost()
    {
        if (NewCheep == null)
        {
            return LocalRedirect(Url.Content("/private"));
        }
        var cheepToPost = new CheepDTO(Guid.NewGuid().ToString(), NewCheep, User.Identity?.Name!, DateTime.UtcNow.ToString());
        
        await _cheepRepo.CreateCheep(cheepToPost);
        return RedirectToPage(RedirectUrl);
    }

    public async Task<bool> FindIsUserFollowingAuthor(string authorUsername, string username)
    {
        return await _authorRepo.IsUserFollowingAuthor(authorUsername, username);
    }

    public async Task<IActionResult> OnPostFollowAuthor(string author)
    {
        await _authorRepo.Follow(User.Identity?.Name!, author);
        return RedirectToPage(RedirectUrl);
    }

    public async Task<IActionResult> OnPostUnfollowAuthor(string author)
    {
        await _authorRepo.Unfollow(User.Identity?.Name!, author);
        return RedirectToPage(RedirectUrl);
    }

    public async Task<IActionResult> OnPostLikeCheep(string cheepId)
    {
        await _cheepRepo.Like(cheepId, User.Identity?.Name!);
        return RedirectToPage(RedirectUrl);
    }

    public async Task<IActionResult> OnPostDislikeCheep(string cheepId)
    {
        await _cheepRepo.Dislike(cheepId, User.Identity?.Name!);
        return RedirectToPage(RedirectUrl);
    }

    public async Task<int> GetCheepLikesCount(string cheepId)
    {
        return await _cheepRepo.GetLikesCount(cheepId);
    }

    public async Task<bool> HasUserLikedCheep(string cheepId)
    {
        return await _cheepRepo.HasUserLikedCheep(cheepId, User.Identity?.Name!);
    }

    /// <summary>
    /// Formats the timestamp to remove unnecessary trailing zeros.
    /// </summary>
    /// <param name="timestamp"></param>
    /// <returns>The formatted timestamp</returns>
    public string FormatTimestamp(string timestamp)
    {
        if (timestamp.EndsWith(".0000000"))
        {
            return timestamp.Substring(0, timestamp.Length - 8);
        }
        return timestamp;
    }
}

src/Chirp.Web/Pages/Public.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Chirp.Core;
using System.ComponentModel.DataAnnotations;

namespace Chirp.Web.Pages;

/// <summary>
/// Razor page representing the public timeline of an author.
/// </summary>
[AllowAnonymous]
public class PublicModel : PageModel
{
    private readonly ICheepRepository _cheepRepo;
    private readonly IAuthorRepository _authorRepo;

    // <summary>
    /// Gets or sets the list of cheeps displayed on a private timeline.
    /// </summary>
    public List<CheepDTO> Cheeps { get; set; }

    /// <summary>
    /// Gets or sets a dictionary saying whether a user is following an author or not.
    /// </summary>
    public Dictionary<string, bool>? IsUserFollowingAuthor { get; set; }

    /// <summary>
    /// Gets or sets the total cheeps. 
    /// </summary>
    public int TotalCheeps { get; set; }

    /// <summary>
    /// Gets or sets the current page number.
    /// </summary>
    public int PageNumber { get; set; }

    /// <summary>
    /// Gets or sets the number of cheeps allowed per page.
    /// </summary>
    public int CheepsPerPage { get; set; }

    /// <summary>
    /// Gets or sets a new cheep.
    /// </summary>
    [BindProperty]
    public string? NewCheep { get; set; }

    /// <summary>
    /// Initializes a new instance of public timeline.
    /// </summary>
    /// <param name="cheepRepo"></param>
    /// <param name="authorRepo"></param>
    public PublicModel(ICheepRepository cheepRepo, IAuthorRepository authorRepo)
    {
        Cheeps = new();
        _cheepRepo = cheepRepo;
        _authorRepo = authorRepo;
        PageNumber = 1;
        CheepsPerPage = 32;
    }

    /// <summary>
    /// Handles HTTP GET requests for the private timeline.
    /// </summary>
    /// <param name="pageNumber"></param>
    /// <returns>The IActionResult representing the result of the operation.</returns>
    public async Task<ActionResult> OnGet(int? pageNumber)
    {
        if (pageNumber.HasValue)
        {
            PageNumber = pageNumber.Value;
        }

        TotalCheeps = await _cheepRepo.GetTotalCheepCount();
        Cheeps = await _cheepRepo.GetCheeps(CheepsPerPage, PageNumber);

        if (User.Identity?.IsAuthenticated == true)
        {
            IsUserFollowingAuthor = new();
            foreach (CheepDTO cheep in Cheeps)
            {
                IsUserFollowingAuthor[cheep.author] = await FindIsUserFollowingAuthor(cheep.author, User.Identity?.Name!);
            }
        }

        return Page();
    }

    /// <summary>
    /// Handles HTTP POST requests for the private timeline.
    /// </summary>
    /// <returns>The IActionResult representing the result of the operation.</returns>
    public async Task<IActionResult?> OnPost()
    {

        if (NewCheep == null)
        {
            return LocalRedirect(Url.Content("~/"));
        }
        var cheepToPost = new CheepDTO(Guid.NewGuid().ToString(), NewCheep!, User.Identity?.Name!, DateTime.UtcNow.ToString());

        await _cheepRepo.CreateCheep(cheepToPost);
        return LocalRedirect(Url.Content("~/")); //Go to profile after posting a cheep
    }

    public async Task<bool> FindIsUserFollowingAuthor(string authorUsername, string username)
    {
        return await _authorRepo.IsUserFollowingAuthor(authorUsername, username);
    }

    public async Task<IActionResult> OnPostFollowAuthor(string author)
    {
        await _authorRepo.Follow(User.Identity?.Name!, author);
        return LocalRedirect(Url.Content("~/"));
    }

    public async Task<IActionResult> OnPostUnfollowAuthor(string author)
    {
        await _authorRepo.Unfollow(User.Identity?.Name!, author);
        return LocalRedirect(Url.Content("~/"));
    }

    public async Task<IActionResult> OnPostLikeCheep(string cheepId)
    {
        await _cheepRepo.Like(cheepId, User.Identity?.Name!);
        return LocalRedirect(Url.Content("~/"));
    }

    public async Task<IActionResult> OnPostDislikeCheep(string cheepId)
    {
        await _cheepRepo.Dislike(cheepId, User.Identity?.Name!);
        return LocalRedirect(Url.Content("~/"));
    }

    public async Task<int> GetCheepLikesCount(string cheepId)
    {
        return await _cheepRepo.GetLikesCount(cheepId);
    }

    public async Task<bool> HasUserLikedCheep(string cheepId)
    {
        return await _cheepRepo.HasUserLikedCheep(cheepId, User.Identity?.Name!);
    }

    /// <summary>
    /// Formats the timestamp to remove unnecessary trailing zeros.
    /// </summary>
    /// <param name="timestamp"></param>
    /// <returns>The formatted timestamp</returns>
    public string FormatTimestamp(string timestamp)
    {
        if (timestamp.EndsWith(".0000000"))
        {
            return timestamp.Substring(0, timestamp.Length - 8);
        }
        return timestamp;
    }

}

src/Chirp.Web/Pages/UserInformation.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Chirp.Infrastructure;
using Chirp.Core;

namespace Chirp.Web.Pages;

/// <summary>
/// Razor page arepresenting an authors user information page.
/// </summary>
public class UserInformationModel : PageModel
{
    private readonly UserManager<Author> _userManager;
    private readonly SignInManager<Author> _signInManager;
    private readonly IAuthorRepository _authorRepo;

    /// <summary>
    /// Gets or sets the following of an author.
    /// </summary>
    public List<AuthorDTO>? Following { get; set; }

    /// <summary>
    /// Initializes a new instance of public timeline.
    /// </summary>
    /// <param name="userManager"></param>
    /// <param name="signInManager"></param>
    /// <param name="authorRepo"></param>
    public UserInformationModel(UserManager<Author> userManager, SignInManager<Author> signInManager, IAuthorRepository authorRepo)
    {
        _userManager = userManager;
        _signInManager = signInManager;
        _authorRepo = authorRepo;
    }

    /// <summary>
    /// Handles HTTP GET requests for the user information page.
    /// </summary>
    /// <returns>The IActionResult representing the result of the operation.</returns>
    public async Task<ActionResult> OnGet()
    {
        Following = await _authorRepo.GetFollowing(User.Identity?.Name!);
        return Page();
    }

    /// <summary>
    /// Handles HTTP POST requests for the user information page.
    /// </summary>
    /// <returns>The IActionResult representing the result of the operation.</returns>
    public async Task<IActionResult> OnPostForgetUser()
    {
        var user = await _userManager.GetUserAsync(User);
        if (user != null)
        {
            await _userManager.DeleteAsync(user);
            await _signInManager.SignOutAsync();
        }
        return LocalRedirect(Url.Content("~/"));
    }
}


src/Chirp.Web/Pages/UserTimeline.cshtml.cs
using Chirp.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Chirp.Web.Pages;

/// <summary>
/// Razor page representing the user timeline.
/// </summary>
[AllowAnonymous]
public class UserTimelineModel : PageModel
{
    private readonly ICheepRepository _cheepRepo;
    private readonly IAuthorRepository _authorRepo;

    /// <summary>
    /// Gets or sets the list of cheeps displayed on a user timeline.
    /// </summary>
    public List<CheepDTO> Cheeps { get; set; }

    /// <summary>
    /// Gets or sets a dictionary saying whether a user is following an author or not.
    /// </summary>
    public Dictionary<string, bool>? IsUserFollowingAuthor { get; set; }

    /// <summary>
    /// Gets or sets the total cheeps. 
    /// </summary>
    public int TotalCheeps { get; set; }

    /// <summary>
    /// Gets or sets the current page number.
    /// </summary>
    public int PageNumber { get; set; }

    /// <summary>
    /// Gets or sets the number of cheeps allowed per page.
    /// </summary>
    public int CheepsPerPage { get; set; }

    /// <summary>
    /// Gets or sets the redirection URL.
    /// </summary>
    public string? RedirectUrl { get; set; }
    
    /// <summary>
    /// Gets or sets a new cheep.
    /// </summary>
    [BindProperty]
    public string? NewCheep { get; set; }

    /// <summary>
    /// Initializes a new instance of user timeline.
    /// </summary>
    /// <param name="cheepRepo"></param>
    /// <param name="authorRepo"></param>
    public UserTimelineModel(ICheepRepository cheepRepo, IAuthorRepository authorRepo)
    {
        Cheeps = new();
        _cheepRepo = cheepRepo;
        _authorRepo = authorRepo;
        PageNumber = 1;
        CheepsPerPage = 32;
    }

    /// <summary>
    /// Handles HTTP GET requests for the user timeline.
    /// </summary>
    /// <param name="author"></param>
    /// <param name="pageNumber"></param>
    /// <returns>The IActionResult representing the result of the operation.</returns>
    public async Task<ActionResult> OnGet(string author, int? pageNumber)
    {
        if (pageNumber.HasValue)
        {
            PageNumber = pageNumber.Value;
        }

        TotalCheeps = await _authorRepo.GetTotalCheepCountFromAuthor(author);
        Cheeps = await _cheepRepo.GetCheepsFromAuthor(author, CheepsPerPage, PageNumber);

        if (User.Identity?.IsAuthenticated == true)
        {
            IsUserFollowingAuthor = new();
            foreach (CheepDTO cheep in Cheeps)
            {
                IsUserFollowingAuthor[cheep.author] = await FindIsUserFollowingAuthor(cheep.author, User.Identity?.Name!);
            }
        }

        RedirectUrl ??= Url.Content($"/{author}");
        return Page();
    }

    /// <summary>
    /// Handles HTTP POST requests for the user timeline.
    /// </summary>
    /// <returns>The IActionResult representing the result of the operation.</returns>
    public async Task<IActionResult> OnPost()
    {
        if (NewCheep! == null)
        {
           return RedirectToPage(RedirectUrl);
        }
        var cheepToPost = new CheepDTO(Guid.NewGuid().ToString(), NewCheep!, User.Identity?.Name!, DateTime.UtcNow.ToString());

        await _cheepRepo.CreateCheep(cheepToPost);
        return RedirectToPage(RedirectUrl);
    }

    public async Task<bool> FindIsUserFollowingAuthor(string authorUsername, string username)
    {
        return await _authorRepo.IsUserFollowingAuthor(authorUsername, username);
    }

    public async Task<IActionResult> OnPostFollowAuthor(string author)
    {
        await _authorRepo.Follow(User.Identity?.Name!, author);
        return RedirectToPage(RedirectUrl);
    }

    public async Task<IActionResult> OnPostUnfollowAuthor(string author)
    {
        await _authorRepo.Unfollow(User.Identity?.Name!, author);
        return RedirectToPage(RedirectUrl);
    }

    public async Task<IActionResult> OnPostLikeCheep(string cheepId)
    {
        await _cheepRepo.Like(cheepId, User.Identity?.Name!);
        return RedirectToPage(RedirectUrl);
    }

    public async Task<IActionResult> OnPostDislikeCheep(string cheepId)
    {
        await _cheepRepo.Dislike(cheepId, User.Identity?.Name!);
        return RedirectToPage(RedirectUrl);
    }

    public async Task<int> GetCheepLikesCount(string cheepId)
    {
        return await _cheepRepo.GetLikesCount(cheepId);
    }

    public async Task<bool> HasUserLikedCheep(string cheepId)
    {
        return await _cheepRepo.HasUserLikedCheep(cheepId, User.Identity?.Name!);
    }

    /// <summary>
    /// Formats the timestamp to remove unnecessary trailing zeros.
    /// </summary>
    /// <param name="timestamp"></param>
    /// <returns>The formatted timestamp</returns>
    public string FormatTimestamp(string timestamp)
    {
        if (timestamp.EndsWith(".0000000"))
        {
            return timestamp.Substring(0, timestamp.Length - 8);
        }
        return timestamp;
    }
}

src/Chirp.Web/Pages/PrivateTimeline.cshtml
@page "/private"
@model Chirp.Web.Pages.PrivateTimelineModel
@{
    ViewData["Title"] = "Chirp!";
    Layout = "Shared/_Layout";
    var username = User.Identity?.Name;
}

@using Microsoft.AspNetCore.Identity
@using Chirp.Infrastructure

@inject SignInManager<Author> SignInManager
@inject UserManager<Author> UserManager
@{
    var user = await UserManager.GetUserAsync(User);
}

<div>
    <h2> Your Private Timeline </h2>
    @if (User.Identity != null && User.Identity.IsAuthenticated)
    {
        <div class="cheepbox"
            style="background-color: #ffe6e6; padding: 15px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
            <h3 style="margin-bottom: 10px; font-size: 1.2em; color: #ff6667;">What's on your mind @(User.Identity.Name)?
            </h3>
            <form method="post" style="overflow: hidden;">
                <input type="text" asp-for="NewCheep!" placeholder="They don't chirp. They chirrup."
                    style="width: calc(100% - 80px); padding: 8px; border: 1px solid #ff9999; border-radius: 4px; margin-right: 10px; float: left;">
                <input type="submit" value="Share"
                    style="background-color: #ff6667; color: #fff; margin: 5px; padding: 8px; border: none; border-radius: 2px; cursor: pointer;">
            </form>
        </div>
    }
    @if (Model.Cheeps.Count > 0)
    {
        <ul id="messagelist" class="cheeps">
            @foreach (var cheep in Model.Cheeps)
            {
                <li>
                    <div style="display: flex; justify-content: space-between;">
                        <strong>
                            <a href="/@cheep.author"> @cheep.author </a>
                        </strong>
                        @if (User.Identity?.IsAuthenticated == true && User.Identity.Name != cheep.author)
                        {
                            <div style='display: inline-block;'>
                                @if (Model.IsUserFollowingAuthor?[cheep.author] == true)
                                {
                                    <form style='display: inline-block' method="post" asp-page-handler="UnfollowAuthor"
                                        asp-route-author="@cheep.author">
                                        <button type="submit">Unfollow</button>
                                    </form>
                                }
                                else
                                {
                                    <form style=' display: inline-block;' method="post" asp-page-handler="FollowAuthor"
                                        asp-route-author="@cheep.author">
                                        <button type="submit">Follow</button>
                                    </form>
                                }
                            </div>
                        }
                    </div>
                    <p>
                        @cheep.message
                        <small>&mdash; @cheep.timestamp</small>
                    </p>
                    <div>
                        @if (User.Identity?.IsAuthenticated == true)
                        {
                            <div style='display: inline-block;'>
                                @if (await Model.HasUserLikedCheep(cheep.id) == true)
                                {
                                    <form style='display: inline-block' method="post" asp-page-handler="DislikeCheep"
                                        asp-route-cheepId="@cheep.id">
                                        <button type="submit">Dislike</button>
                                    </form>
                                }
                                else
                                {
                                    <form style='display: inline-block;' method="post" asp-page-handler="LikeCheep"
                                        asp-route-cheepId="@cheep.id">
                                        <button type="submit">Like</button>
                                    </form>
                                }
                                <text style="color: blue;">@await Model.GetCheepLikesCount(cheep.id)</text>
                            </div>
                        }
                    </div>
                </li>
            }
        </ul>

        <!-- Pagination links (horizontal-list)-->
        <nav aria-label="Cheep Pagination">
            <div class="pagination justify-content-center">
                <span class="page-item">
                    <a class="page-link"
                        href="/private?pageNumber=@(Model.PageNumber - 1 > 0 ? Model.PageNumber - 1 : Model.PageNumber)">&lt;</a>
                </span>
                @for (var i = 1; i <= Math.Ceiling((double)Model.TotalCheeps / Model.CheepsPerPage); i++)
                {
                    <span class="page-item @(i == Model.PageNumber ? "active" : "")">
                        <a class="page-link" href="/private?pageNumber=@i">@i</a>
                    </span>
                }
                <span class="page-item">
                    <a class="page-link"
                        href="/private?pageNumber=@(Model.PageNumber + 1 <= Math.Ceiling((double)Model.TotalCheeps / Model.CheepsPerPage) ? Model.PageNumber + 1 : Model.PageNumber)">&gt;</a>
                </span>
            </div>
        </nav>

    }
    else
    {
        <em>There are no cheeps so far.</em>
    }
</div>

src/Chirp.Web/Pages/Public.cshtml
@page "/"
@model Chirp.Web.Pages.PublicModel
@{
    ViewData["Title"] = "Chirp!";
    Layout = "Shared/_Layout";
}

<div>
    <h2> Public Timeline </h2>
    @if (User.Identity != null && User.Identity.IsAuthenticated)
    {
        <div class="cheepbox"
            style="background-color: #ffe6e6; padding: 15px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
            <h3 style="margin-bottom: 10px; font-size: 1.2em; color: #ff6667;">What's on your mind @(User.Identity.Name)?
            </h3>
            <form method="post" style="overflow: hidden;">
                <input type="text" asp-for="NewCheep!" placeholder="They don't chirp. They chirrup."
                    style="width: calc(100% - 80px); padding: 8px; border: 1px solid #ff9999; border-radius: 4px; margin-right: 10px; float: left;">
                <input type="submit" value="Share"
                    style="background-color: #ff6667; color: #fff; margin: 5px; padding: 8px; border: none; border-radius: 2px; cursor: pointer;">
            </form>
        </div>
    }

    @if (Model.Cheeps.Count > 0)
    {
        <ul id="messagelist" class="cheeps">
            @foreach (var cheep in Model.Cheeps)
            {
                <li>
                    <div style="display: flex; justify-content: space-between;">
                        <strong>
                            <a href="/@cheep.author"> @cheep.author </a>
                        </strong>
                        @if (User.Identity?.IsAuthenticated == true && User.Identity.Name != cheep.author)
                        {
                            <div style='display: inline-block;'>
                                @if (Model.IsUserFollowingAuthor?[cheep.author] == true)
                                {
                                    <form style='display: inline-block' method="post" asp-page-handler="UnfollowAuthor"
                                        asp-route-author="@cheep.author">
                                        <button type="submit">Unfollow</button>
                                    </form>
                                }
                                else
                                {
                                    <form style=' display: inline-block;' method="post" asp-page-handler="FollowAuthor"
                                        asp-route-author="@cheep.author">
                                        <button type="submit">Follow</button>
                                    </form>
                                }
                            </div>
                        }
                    </div>
                    <p>
                        @cheep.message
                        <small>&mdash; @Model.FormatTimestamp(cheep.timestamp)</small>
                    </p>
                    <div>
                        @if (User.Identity?.IsAuthenticated == true)
                        {
                            <div style='display: inline-block;'>
                                @if (await Model.HasUserLikedCheep(cheep.id) == true)
                                {
                                    <form style='display: inline-block' method="post" asp-page-handler="DislikeCheep"
                                        asp-route-cheepId="@cheep.id">
                                        <button type="submit">Dislike</button>
                                    </form>
                                }
                                else
                                {
                                    <form style='display: inline-block;' method="post" asp-page-handler="LikeCheep"
                                        asp-route-cheepId="@cheep.id">
                                        <button type="submit">Like</button>
                                    </form>
                                }
                                <text style="color: blue;">@await Model.GetCheepLikesCount(cheep.id)</text>
                            </div>
                        }
                    </div>
                </li>
            }
        </ul>

        <!-- Pagination links (horizontal-list)-->
        <nav aria-label="Cheep Pagination">
            <div class="pagination justify-content-center">
                <span class="page-item">
                    <a class="page-link"
                        href="/?pageNumber=@(Model.PageNumber - 1 > 0 ? Model.PageNumber - 1 : Model.PageNumber)">&lt;</a>
                </span>
                @for (var i = 1; i <= Math.Ceiling((double)Model.TotalCheeps / Model.CheepsPerPage); i++)
                {
                    <span class="page-item @(i == Model.PageNumber ? "active" : "")">
                        <a class="page-link" href="/?pageNumber=@i">@i</a>
                    </span>
                }
                <span class="page-item">
                    <a class="page-link"
                        href="/?pageNumber=@(Model.PageNumber + 1 <= Math.Ceiling((double)Model.TotalCheeps / Model.CheepsPerPage) ? Model.PageNumber + 1 : Model.PageNumber)">&gt;</a>
                </span>
            </div>
        </nav>
    }
    else
    {
        <em>There are no cheeps so far.</em>
    }
</div>

src/Chirp.Web/Pages/UserInformation.cshtml
@page
@model Chirp.Web.Pages.UserInformationModel
@{
    ViewData["Title"] = "Chirp!";
    Layout = "Shared/_Layout";
}

@using Microsoft.AspNetCore.Identity
@using Chirp.Infrastructure

@inject SignInManager<Author> SignInManager
@inject UserManager<Author> UserManager
@{
    var user = await UserManager.GetUserAsync(User);
}

<div>
    <p>
        Name: @UserManager.GetUserName(User)
    </p>
    <p>
        Email: @(await UserManager.GetEmailAsync(user ?? throw new ArgumentNullException(nameof(user))))
    </p>

    <p>
        Following <strong>@(Model.Following?.Count ?? 0)</strong>:
    </p>
    <ul id="followedlist" class="following">
        @if (Model.Following != null)
        {
            @foreach (var followed in Model.Following)
            {
               <li>
                <p>
                    <a style="color: black;" href="/@followed.name">@followed.name</a>
                </p>
              </li>
            }
        }
    </ul>
    <button class="form-group">
        <a id="manage" class="nav-link text-dark" href="/@UserManager.GetUserName(User)" title="Manage">Your Cheeps</a>
    </button>

    <form method="post" asp-page-handler="ForgetUser">
        <button style="color: red; margin-top: 5px">
            Forget me!
        </button>
    </form>
</div>